################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
Driver/source/F2837xD_Adc.obj: ../Driver/source/F2837xD_Adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_Adc.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_CodeStartBranch.obj: ../Driver/source/F2837xD_CodeStartBranch.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_CodeStartBranch.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_CpuTimers.obj: ../Driver/source/F2837xD_CpuTimers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_CpuTimers.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_DefaultISR.obj: ../Driver/source/F2837xD_DefaultISR.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_DefaultISR.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_ECap.obj: ../Driver/source/F2837xD_ECap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_ECap.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_EPwm.obj: ../Driver/source/F2837xD_EPwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_EPwm.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_GlobalVariableDefs.obj: ../Driver/source/F2837xD_GlobalVariableDefs.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_GlobalVariableDefs.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_Gpio.obj: ../Driver/source/F2837xD_Gpio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_Gpio.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_PieCtrl.obj: ../Driver/source/F2837xD_PieCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_PieCtrl.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_PieVect.obj: ../Driver/source/F2837xD_PieVect.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_PieVect.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_Spi.obj: ../Driver/source/F2837xD_Spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_Spi.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_SysCtrl.obj: ../Driver/source/F2837xD_SysCtrl.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_SysCtrl.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

Driver/source/F2837xD_usDelay.obj: ../Driver/source/F2837xD_usDelay.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: C2000 Compiler'
	"D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 -Ooff --opt_for_speed=0 --fp_mode=relaxed --fp_reassoc=on --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/include/Constants" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Control" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/FLASH_API/src" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Parameter" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Sensor" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/HardWare" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-CPU/C28x/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uC-LIB" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-CORE" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/AlgorithmLibrary" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Ports/C28x/Generic/CCS" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/uCOS-II/Source" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include1" --include_path="F:/project/ti/C2000/BirdFlight_V3.0.5/Driver/include/include2" --include_path="D:/ti/ccsv8/tools/compiler/ti-cgt-c2000_18.1.1.LTS/include" --advice:performance=all -g --diag_warning=225 --diag_wrap=off --display_error_number --preproc_with_compile --preproc_dependency="Driver/source/F2837xD_usDelay.d_raw" --obj_directory="Driver/source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


